### ISSUE TITLE
Deployment showing unfinished page

### ISSUE THREAD

**Issue by ViaTheCode** [imd1005-web-development-winter-2023/assignment-02-Viaviaviaviaviavia#2]
@neilmispelaar 
Hello,
I've finished my assignment and I uploaded it to github but when I try to deploy it the link goes to a half finished version of the website.
I'm not sure what I am doing wrong, the code I uploaded is the finished version.

**Comment by neilmispelaar** [comment]
Hi @Viaviaviaviaviavia , 

Will have a quick look right now.

**Comment by neilmispelaar** [comment]
Wow! This looks absolutely amazing. 

It's possible it just took a few minutes for the deploys to go through. 

Just remember to hit CTRL (Control) + F5 to force your browser to do a full refresh of the page after each version is deployed. 

![Screenshot 2023-02-18 at 16-34-29 Assignment 02](https://user-images.githubusercontent.com/9325038/219900496-0ab226ad-12a2-41f1-9926-32d114ca9a71.jpg)

**Comment by ViaTheCode** [comment]
Ah, thank you!
I'm glad that it's working now :)

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by neilmispelaar** [comment]
🎉This is so awesome. Well done! 

I'll close the issue if there isn't anything else. (If you need anything else feel free to open another issue)
